export const DISCOVER_MANGA_REQUEST = 'DISCOVER_MANGA_REQUEST';
export const DISCOVER_MANGA_SUCCESS = 'DISCOVER_MANGA_SUCCESS';
export const DISCOVER_MANGA_FAILURE = 'DISCOVER_MANGA_FAILURE';

export const DISCOVER_MANGA_PAGINATED_SUCCESS =
  'DISCOVER_MANGA_PAGINATED_SUCCESS';
