export const SELECT_MANGA_REQUEST = 'SELECT_MANGA_REQUEST';
export const SELECT_MANGA_SUCCESS = 'SELECT_MANGA_SUCCESS';
export const SELECT_MANGA_FAILURE = 'SELECT_MANGA_FAILURE';
export const SELECT_MANGA = 'SELECT_MANGA';

export const REVERSE_CHAPTERS = 'REVERSE_CHAPTERS';
