export const SEARCH_MANGA_REQUEST = 'SEARCH_MANGA_REQUEST';
export const SEARCH_MANGA_SUCCESS = 'SEARCH_MANGA_SUCCESS';
export const SEARCH_MANGA_FAILURE = 'SEARCH_MANGA_FAILURE';

export const SEARCH_MANGA_PAGINATED_SUCCESS = 'SEARCH_MANGA_PAGINATED_SUCCESS';