export const SEARCH_MANGA_REQUEST = 'SEARCH_MANGA_REQUEST';
export const SEARCH_MANGA_SUCCESS = 'SEARCH_MANGA_SUCCESS';
export const SEARCH_MANGA_FAILURE = 'SEARCH_MANGA_FAILURE';

export const SEARCH_MANGA_PAGINATED_SUCCESS = 'SEARCH_MANGA_PAGINATED_SUCCESS';

export const sources = {
  MANGANATO: 'MANGANATO',
  MANGADEX: 'MANGADEX',
};

export const SET_SEARCH_SOURCE = 'SET_SEARCH_SOURCE';

// actions specific to manga dex source
export const SEARCH_MANGA_DEX_SUCCESS = 'SEARCH_MANGA_DEX_SUCCESS';
export const SEARCH_MANGA_DEX_PAGINATED_SUCCESS = 'SEARCH_MANGA_DEX_PAGINATED_SUCCESS';