export const FETCH_CHAPTER_REQUEST = 'FETCH_CHAPTER_REQUEST';
export const FETCH_CHAPTER_SUCCESS = 'FETCH_CHAPTER_SUCCESS';
export const FETCH_CHAPTER_FAILURE = 'FETCH_CHAPTER_FAILURE';

export const VIEW_CHAPTER = 'VIEW_CHAPTER';

export const LOAD_CHAPTER_UPDATES = 'LOAD_CHAPTER_UPDATES';
export const SET_CHAPTER_UPDATE = 'SAVE_CHAPTER_UPDATE';
